name: Deployment Workflow

on:
  push:
    branches: [main]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: SSH Connection
        uses: appleboy/ssh-action@master
        with:
          host: solarsocket.solartweaks.com
          username: root
          key: ${{ secrets.SSH_SECRET }}
          port: 22
          script_stop: true
          script: |
            /root/SolarTweaks/updaters/solartweaksassistant.sh
